#!/bin/sh

# arch install
# https://dimanao.org/ustanovka-arch-linux-uefi-grub/
# https://wiki.archlinux.org/index.php/Installation_guide

#	- розкоментувати форматування, якщо потрібно
# 	- замінити sdw на потрібний диск
# 	- замінити користувача і його ID
# 	- замінити паролі
# 	- підставити потрібний графічний драйвер
#	- опції монтування для SSD
#	- замінити hostname і domain
# 	- прослідкувати відповідність розділів на диску
#	- годинник в utc

#	- install appmenu

# 	визначаємо драйвер відеокарти і підставляємо в уcтановку X 
# 	lspci | grep -e VGA -e 3D

# перевіряємо ping
# запускаємо fdisk

INSDIR="archInstaller"
USERNAME="ih"
USER_ID="" # -u 1000
PASSPHRASE="af"
CONSOLE_FONT="ter-v16n" # ter-v18b for leptop
SSD="" # discard
HOST_NAME="archlinux"
DOMAIN="vbox"
THEMING="# "
ADD_INSTALL="# "

mkdir $INSDIR
cd $INSDIR


############
# Install script
###

cat > 01-install.sh << EOF
#!/bin/sh

	# Wipe the MBR:
  	# dd if=/dev/zero of=/dev/sdw bs=512 count=1

	# /sbin/fdisk /dev/sdw << EOf
	# g
	# n
	# 1

	# +20M
	# t
	# 1
	# n
	# 2


	# w
# EOf

# mkfs.ext4 /dev/sdw2
mount -o $SSD,noatime /dev/sdw2 /mnt

# mkfs.fat -F32 /dev/sdw1
mkdir -p /mnt/boot/efi
mount -o $SSD,noatime /dev/sdw1 /mnt/boot/efi

pacstrap -i /mnt base linux-lts linux-firmware grub grub-theme-vimix efibootmgr terminus-font networkmanager sudo neovim zsh
genfstab -U /mnt >> /mnt/etc/fstab

mv ../$INSDIR /mnt/root/
# cp -r ../$INSDIR /mnt/root/
echo "go to /root/$INSDIR"
arch-chroot /mnt /bin/bash

EOF


############
# Config script
###

cat > 02-setupChroot.sh << EOF
#!/usr/bin/env bash

echo "en_US.UTF-8 UTF-8" > /etc/locale.gen && echo "uk_UA.UTF-8 UTF-8" >> /etc/locale.gen
locale-gen
echo "LANG=uk_UA.UTF-8" > /etc/locale.conf
echo "FONT=$CONSOLE_FONT" > /etc/vconsole.conf
# echo -e "MODULES=(btrfs nvme nvidia)\nHOOKS=(autodetect systemd)\nCOMPRESSION=\"cat\"" > /etc/mkinitcpio.conf
# mkinitcpio -p linux-lts # Создание образа ранней загрузки
echo "$HOST_NAME" > /etc/hostname # Задаём имя компьютера
echo -e "127.0.0.1	localhost\n::1		localhost\n127.0.1.1	$HOST_NAME.$DOMAIN	$HOST_NAME" > /etc/hosts
echo "GRUB_THEME=/usr/share/grub/themes/Vimix/theme.txt" >> /etc/default/grub
ln -sf /usr/share/zoneinfo/Europe/Kiev /etc/localtime
hwclock --systohc --localtime # hwclock --systohc --utc (для установки одной системы)
grub-install /dev/sdw
grub-mkconfig -o /boot/grub/grub.cfg
# efibootmgr -d /dev/nvme0n1 -p 1 -c -L "Arch Linux" -l /vmlinuz-linux -u "root=/dev/nvme0n1p2 rw quiet rootflags=subvol=@root initrd=/intel-ucode.img initrd=/initramfs-linux.img"
# sh -c "sed -i '/\[multilib\]/,/Include/s/^[ ]*#//' /etc/pacman.conf"
echo "root:$PASSPHRASE" | chpasswd # Пароль для суперпользователя

# vmware intel amdgpu ati nouveau xorg-drivers
pacman -S tree mc git \
noto-fonts ttf-hack termite lightdm-gtk-greeter-settings gtk-engines gtk-engine-murrine \
xorg-server xf86-video- \
pulseaudio pulseaudio-alsa pavucontrol alsa-lib alsa-utils \
firefox-i18n-uk \
network-manager-applet exo garcon thunar thunar-volman tumbler xfce4-appfinder xfce4-panel \
xfce4-power-manager xfce4-session xfce4-settings xfconf xfdesktop xfwm4 thunar-archive-plugin \
thunar-media-tags-plugin xfce4-clipman-plugin xfce4-mpc-plugin xfce4-notifyd xfce4-screensaver \
xfce4-screenshooter xfce4-whiskermenu-plugin xfce4-pulseaudio-plugin xfce4-xkb-plugin gvfs plank \
catfish file-roller p7zip unrar viewnior appmenu-gtk-module \
--noconfirm --noprogressbar --quiet

git clone https://Igor-slacker@bitbucket.org/Igor-slacker/dotfiles.git
cp -r dotfiles/defaultConfig/{etc,root,usr} /
sh dotfiles/defaultConfig/initEtcXdgXfce

$THEMINGsh 03-setupThemes.sh
$ADD_INSTALLsh 04-additionalInstall.sh

useradd -m -g users -G wheel $USER_ID -s /bin/zsh $USERNAME # Создание нового пользователя
echo "$USERNAME:$PASSPHRASE" | chpasswd # Пароль для пользователя
sh -c "sed -i 's/^# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/g' /etc/sudoers"

sh -c "sed -i 's/#greeter-session=example-gtk-gnome/greeter-session=lightdm-gtk-greeter/' /etc/lightdm/lightdm.conf"
echo -e "cursor-theme-name = breeze_cursors\n" >> /etc/lightdm/lightdm-gtk-greeter.conf

systemctl enable NetworkManager
systemctl enable lightdm

cd /root
rm $INSDIR/{01-install.sh,02-setupChroot.sh}
mv /root/$INSDIR /home/$USERNAME/
chown -hR $USERNAME:users /home/$USERNAME/$INSDIR
chsh -s /bin/zsh
echo "install appmenu"

EOF

# pacman -S nvidia nvidia-settings nvidia-utils opencl-nvidia opencl-headers lib32-nvidia-utils lib32-opencl-nvidia --noconfirm --noprogressbar --quiet # Установка драйверов Nvidia


############
# Config themes
###

cat > 03-setupThemes.sh << EOF

#!/bin/bash

echo -e '<?xml version="1.0" encoding="UTF-8"?>\n\n<channel name="xfwm4" version="1.0">\n  <property name="general" type="empty">\n    <property name="theme" type="string" value="Mojave-light"/>\n  </property>\n</channel>\n' > /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xfwm4.xml
echo -e '<?xml version="1.0" encoding="UTF-8"?>\n\n<channel name="xsettings" version="1.0">\n  <property name="Net" type="empty">\n    <property name="ThemeName" type="string" value="Mojave-light"/>\n    <property name="IconThemeName" type="string" value="Luna-Light"/>\n  </property>\n</channel>\n' > /etc/skel/.config/xfce4/xfconf/xfce-perchannel-xml/xsettings.xml
echo -e 'theme-name = Mojave-light\nbackground = #204a87\nicon-theme-name = Luna-Light\nposition = 50%,end 50%,start\n' >> /etc/lightdm/lightdm-gtk-greeter.conf

tar -C /usr/share/icons/ -xvf Luna-Icons.tar.xz Luna Luna-Light
tar -C /usr/share/themes/ -xvf Mojave-light.tar.xz

EOF


############
# Config after install
###

cat > 04-additionalInstall.sh << EOF

#!/bin/bash

# pacman -S --needed base-devel --noconfirm --noprogressbar --quiet
# git clone https://aur.archlinux.org/yay.git
# cd yay
# makepkg -si
# cd ..
# yay -Syu vala-panel-appmenu-xfce-git lightdm-slick-greeter

pacman -U vala-panel-appmenu*

EOF


rm ../arch_install
cp ../* $INSDIR/
