#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

usr/bin/lxqt-policykit-agent &
usr/bin/lxqt-powermanagement &
usr/bin/lxqt-notificationd &
nm-tray &
# xiccd &
xwallpaper --zoom /usr/share/backgrounds/KDE\ Plasma\ Dark\ 285\ HD\ WL.jpg &
$HOME/.config/polybar/launch.sh &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Falkon desktop='^1'
bspc rule -a Vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

