#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

/usr/lib/polkit-kde-authentication-agent-1 &
/usr/lib/org_kde_powerdevil &
xiccd &
xwallpaper --maximize /usr/share/backgrounds/KDE Plasma Dark 285 HD WL &
$HOME/.config/polybar/launch.sh &
picom &

bspc monitor -d 1 2 3 4 5 6 7 8 9

bspc config border_width         2
bspc config window_gap           4

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^1'
bspc rule -a Vlc state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

