[colors.bright]
black = "#709080"
blue = "#94bff3"
cyan = "#93e0e3"
green = "#c3bf9f"
magenta = "#ec93d3"
red = "#dca3a3"
white = "#ffffff"
yellow = "#f0dfaf"

[colors.normal]
black = "#3f3f3f"
blue = "#506070"
cyan = "#8cd0d3"
green = "#60b48a"
magenta = "#dc8cc3"
red = "#705050"
white = "#dcdccc"
yellow = "#dfaf8f"

[colors.primary]
background = "#3f3f3f"
foreground = "#dcdccc"

[cursor.style]
blinking = "On"

[window.padding]
x = 5
y = 5
